### ISSUE TITLE
v7 to v8 - search for locations doesn't work

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#106]
![image](https://user-images.githubusercontent.com/8801702/107480185-4df1e480-6bd0-11eb-8c72-2a4341792fce.png)

**Comment by nf-s** [comment]
Fixed - related to https://github.com/TerriaJS/RaPPMap/issues/107

Had to update bingMapKey

**Comment by juan-guerschman** [comment]
still not working for me in https://beta.geo-rapp.terria.io/ 
Maybe related to Bing maps not working

**Comment by juan-guerschman** [comment]
works fine
